// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcoqowomchjvpyhjqkqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjb3Fvd29tY2hqdnB5aGpxa3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NjM4OTIsImV4cCI6MjA2MjMzOTg5Mn0.ulODkIAHUFaNRVN2egai5PG1RPgPB19OjRQVBPNqd84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);